Livraria3/Models/ModLivro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Livraria3.Models
{
    public class ModLivro
    {

        [Required(ErrorMessage="Este campo é obrigatório")]
        [DisplayName("Código do livro")]
        public string codLivro { get; set; }


        [Required(ErrorMessage = "Este campo é obrigatório")]
        [DisplayName("Nome do livro")]
        public string nomeLivro { get; set; }


        [Required(ErrorMessage = "Este campo é obrigatório")]
        [DisplayName("Código do autor")]
        public string codAutor { get; set; }


        [Required(ErrorMessage = "Este campo é obrigatório")]
        [DisplayName("Nome do autor")]
        public string nomeAutor { get; internal set; }


        [Required(ErrorMessage = "Este campo é obrigatório")]
        [DisplayName("Status")]
        public object status { get; internal set; }
    }
}

Livraria3/Controllers/HomeController.cs
using Livraria3.Dados;
using Livraria3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Livraria3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CadAutor()
        {
            return View();
        }

        AcAutores acoes = new AcAutores();//instancia de classe
        ModLivro modelo = new ModLivro();//instancia de classe

        public ActionResult ConfCadAutor(FormCollection frm)
        {
            modelo.nomeAutor = frm["txtNmAutor"];
            modelo.status = frm["txtSta"];

            acoes.inserirAutor(modelo);

            return View();
        }

        public ActionResult AtAutor()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AtAutor(FormCollection frm, string btn)
        {
            modelo.codAutor = frm["txtCodAutor"];
            if (btn == "Buscar")
            {
                acoes.BuscarAutor(modelo);
                ViewBag.cod = modelo.codAutor;
                ViewBag.nome = modelo.nomeAutor;
                ViewBag.sta = modelo.status;

                return View();
            }
            else if (btn == "Atualizar")
            {
                modelo.nomeAutor = frm["txtNmAutor"];
                modelo.status = frm["txtSta"];

                acoes.atualizarAutor(modelo);

                ViewBag.msg = "Autor atualizado.";

                return View();
            }
            else if (btn == "Exluir")
            {
                acoes.excluirAutor(modelo);

                ViewBag.msg = "Autor excluído";

                return View();
            }
            else
            {
                return View();
            }

        }
    }
}

Livraria3/Controllers/LivrariaController.cs
using Livraria3.Dados;
using Livraria3.Models;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Livraria3.Controllers
{
    public class LivrariaController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public void CarregaAutores()
        {
            List<SelectListItem> autores = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("server=localhost; database=bdLivraria; user=root; password=12345678"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbAutor where sta=1", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    autores.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });

                }
                con.Close();
                ViewBag.autores = new SelectList(autores, "Value", "Text");
            }
        }

        public ActionResult CadLivro()
        {
            CarregaAutores();
            return View();
        }

        AcLivro ac = new AcLivro();//instancia de classe
        ModLivro mod = new ModLivro();//instancia de classe
        public ActionResult ConfCadLivro(FormCollection frm)
        {
            mod.nomeLivro = frm["txtNmLivro"];
            mod.codAutor = Request["autores"];
            ac.inserirLivro(mod);
            return View();
        }

        public ActionResult consLivro()
        {
            GridView gvAtend = new GridView();
            gvAtend.DataSource = ac.selecionaLivro();
            gvAtend.DataBind();
            StringWriter sw = new StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            gvAtend.RenderControl(htw);
            ViewBag.GridViewString = sw.ToString();
            return View();
        }

        public ActionResult ListarLivro()
        {
            return View(ac.BuscarLivro());
        }


    }
}

Livraria3/Views/Home/AtAutor.cshtml
@{
    ViewBag.Title = "AtAutor";
}

<h2>Atualizar Autor</h2>

@using (Html.BeginForm("AtAutor", "Home", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    <label>Código do autor</label>
    <input type="text" id="txtCodAutor" name="txtCodAutor" value="@ViewBag.cod" />
    <br />

    <label>Nome do autor</label>
    <input type="text" id="txtNmAutor" name="txtNmAutor" value="@ViewBag.nome" />
    <br />

    <label>Status</label>
    <input type="text" id="txtSta" name="txtSta" value="@ViewBag.sta" />
    <br />
    <br />
    <br />
    <input type="submit" value="Buscar" name="btn" class="btn btn-warning" />
    <input type="submit" value="Atualizar" name="btn" class="btn btn-success"/>
    <input type="submit" value="Excluir" name="btn" class="btn btn-danger"/>
}

Livraria3/Views/Home/CadAutor.cshtml
@{
    ViewBag.Title = "CadAutor";
}

<h2>Cadastro do Autor</h2>

@using (Html.BeginForm("ConfCadAutor", "Home", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    <label>Nome do autor:</label>
    <br />
    <input type="text" id="txtNmAutor" name="txtNmAutor" />
    <br />
    <label>Status:</label>
    <br />
    <input type="text" id="txtSta" name="txtSta" />
    <br />
    <br />
    <br />
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}

Livraria3/Views/Home/ConfCadAutor.cshtml
@{
    ViewBag.Title = "Sucesso!";
}

<h2>Cadastro efetuado com sucesso!</h2>

Livraria3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h1>Livraria</h1>

Livraria3/Views/Livraria/CadLivro.cshtml
@model Livraria3.Models.ModLivro

@{
    ViewBag.Title = "CadLivro";
}

<h2>Cadastrar Livro</h2>


@using (Html.BeginForm("ConfCadLivro","Livraria", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.nomeLivro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" id="txtNmLivro" name="txtNmLivro" />
                <br />
                @Html.ValidationMessageFor(model => model.nomeLivro, "", new { @class = "text-danger" })
                <br />
                @Html.DropDownList("autores", "Escolha o autor")
            </div>
           
        </div>
        <br/>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
         
                @Html.ActionLink("Voltar", "Index")
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Livraria3/Views/Livraria/ConfCadLivro.cshtml
@{
    ViewBag.Title = "Sucesso!";
}

<h2>Cadastro efetuado com sucesso!</h2>

Livraria3/Views/Livraria/ListarLivro.cshtml
@model IEnumerable<Livraria3.Models.ModLivro>

@{
    ViewBag.Title = "ListarLivro";
}

<h2>Listar Livro</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codLivro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nomeLivro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.codAutor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nomeAutor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.codLivro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nomeLivro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.codAutor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nomeAutor)
        </td>
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
    </tr>
}

</table>

Livraria3/Views/Livraria/consLivro.cshtml
@{
    ViewBag.Title = "consLivro";
}

<h2>Consultar Livro</h2>

@Html.Raw(ViewBag.GridViewString)

Livraria3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Livraria - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Início", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastrar", "CadLivro", "Livraria")</li>
                    <li>@Html.ActionLink("Consultar", "consLivro", "Livraria")</li>
                    <li>@Html.ActionLink("Listar", "ListarLivro", "Livraria")</li>
                    <li>@Html.ActionLink("Cadastrar Autor", "CadAutor", "Home")</li>
                    <li>@Html.ActionLink("Atualizar Autor", "AtAutor", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Desenvolvedora Beatriz</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>